### ISSUE TITLE
Comments SCSS

### ISSUE THREAD

**Issue by robi09** [Codeinwp/Mooveit-Lite#14]
Vezi ca ai bifat sa iti dea comentarii pentru debuging in SCSS, ex "/\* line 13, sass/_clearfix.scss */" .

**Comment by robciucioan** [comment]
@robi09, tema nu mai are fișierele SCSS. Cum fac aici?

**Comment by robi09** [comment]
@robciucioan  manual, cu tracker in task-ul de management din proiectul 9Pixels ci nu in ti. :) Ar fi bine pe viitor sa pastrezi fisierele, chiar si daca faci un mic update. Tot odata sa fi mai atent la ce faci pls.

Cheers!
