### ISSUE TITLE
text copyright footer

### ISSUE THREAD

**Issue by robi09** [Codeinwp/Mooveit-Lite#41]
"Copyright © Movatique is proudly powered by WordPress. "
- movatique trebuie sa fie numele site-ului
- adauga la sfarsit si Theme: Mooveit Lite.
- adauga link pe wordpress catre wordpress si link pe numele temei catre tema
- toate textele trebuie sa se poata traduce

**Comment by robciucioan** [comment]
@robi09, am rezolvat problema înainte să ajung la acest issue. Nu mai țin minte în ce ID am făcut commit.
