### ISSUE TITLE
add better description and tags

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Mooveit-Lite#44]
add better description and tags

**Comment by robi09** [comment]
Description:
"Free responsive WordPress theme for Dentists"

Tags:
"right sidebar, custom index, customizer, custom-menu, rtl-language-support, sticky-post, translation-ready"

**Comment by ineagu** [comment]
? ce vrei sa zici cu asta ?

**Comment by robi09** [comment]
Asta sa le adauge ionut in css. :)

**Comment by robciucioan** [comment]
@robi09, descrierea "Free responsive WordPress theme for Dentists" cred că e pentru DentaTheme Lite.

**Comment by robciucioan** [comment]
E ok dacă pun descriere asta: "Mooveit Lite is a free responsive WordPress Theme"?
