### ISSUE TITLE
Escape theme options

### ISSUE THREAD

**Issue by Oliviu** [Codeinwp/Mooveit-Lite#68]
@robciucioan , @robi09 
Escape theme options on output.

**Comment by robciucioan** [comment]
@ineagu, nu înțeleg la ce se referă.

**Comment by robi09** [comment]
@ineagu  Ce vrea sa spuna aici?

**Comment by robi09** [comment]
Am aflat la ce refera cu escape 

 If this is plain text, use esc_attr(). If this is a URL, use esc_url(). There are a few instances where the theme does escape things, but for the large majority, it doesn't. Make sure to escape on both front end output as well as in the widget form fields output.

:)
