### ISSUE TITLE
Copyright text correction

### ISSUE THREAD

**Issue by Oliviu** [Codeinwp/Mooveit-Lite#71]
@robciucioan , @robi09 

Copyright text in footer is still incorrect. Try something like this: Copyright &copy; [Website title] | Proudly powered by WordPress

**Comment by robi09** [comment]
Aici ai uitat sa adaugi text domain la: <?php _e( 'Copyright &copy;' ); ?>

**Comment by robi09** [comment]
Am vazut acum ca este rezolvat in #68
