### ISSUE TITLE
SIdebar display message only for logged in users

### ISSUE THREAD

**Issue by Oliviu** [Codeinwp/Mooveit-Lite#72]
@robciucioan , @robi09 

Sidebar notice: "The sidebar is not active.” - could you display this message only for logged in users? Users might simply not want to add any widgets to the sidebar, and that would leave them with this message visible to the visitors.

**Comment by robi09** [comment]
Aici nu inteleg ce ai facut, in issue se specifica sa adagi text-ul "The sidebar is not active." doar pentru userii logati. Tu ai scos textul? Fa te rog sa apara textul doar pentru userii logati cand nu exista sidebar, iar pentru userii nelogati sa nu apara nimic.
