### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by Oliviu** [Codeinwp/Mooveit-Lite#74]
@robciucioan , @robi09 

Theme URI results in 404 error page.

**Comment by robi09** [comment]
http://demo.themeisle.com/mooveit-lite/

**Comment by robciucioan** [comment]
@robi09, cred că tre' link-ul de la prezentarea temei, nu cea de demo.

**Comment by robi09** [comment]
@robciucioan uite aici https://themeisle.com/themes/mooveit-lite
