### ISSUE TITLE
Customizer description

### ISSUE THREAD

**Issue by Oliviu** [Codeinwp/Mooveit-Lite#75]
@robciucioan , @robi09 

It might be a good idea to add some descriptions in Customizer, so that users have a better understanding of what each option does.

**Comment by robi09** [comment]
@ineagu @robciucioan  mie mi se par ok numele la field-uri, nu cred ca este necesar sa mai pierdem in ca 1-2 ore doar ca sa adaugam si descriere la field-uri. @ineagu  ce spui?

**Comment by ineagu** [comment]
@robi09 @robciucioan tema este pe demo ? cum pot vedea cum arata customizerul ?

**Comment by robciucioan** [comment]
@ineagu, link: http://demo.themeisle.com/mooveit-lite/

**Comment by ineagu** [comment]
@robi09 @robciucioan @andreitripon @nikkyandrei este foarte important sa intelegi conceptul de panels introdus in vers de wordpress 4.0 parca si folosit de noi la zerif.

Un panel te lasa sa ai in el mai multe sectiuni si se deschide in tab separat, de ex la aceasta tema ar fi trebuit sa avem panel pt Frontpage iar acolo sa punem sectiuni pt : static frontpage, features boxes, Our clients section

La fel background image merge pus in aceeasi sectiune cu background color, nu are rost o sectiune noua colors cu o singura culoare.

la fel header + header image ar putea fi unite intr-un panel .

Ordinea optiunilor in customizer este f importanta, frontpage ar trebui afisat mai sus cred.

Mai nou in customizer se pot afisa diverse sectiuni in functie de pagina, nu are rost sa afisam panelul de frontpage pe pagina de contact, la fel cum nu are rost sa afisam sectiunea de contact cand userul e pe homepage.

Upsellul nu e facut ok, adica nu e rau, doar ca nu ati folosit acelasi model pe care il folosim noi ( vezi constructzine lite ), unde folosim sectiuni goale, iar ele text + link catre PRO version .

Inainte sa trantiti cod, setari alocati putin timp sa cautati si cea mai eficienta solutie pentru user. Problema este ca deja cand avem 2 teme cu cod diferit, este de 2x mai multa munca necesara pentru a regandi toate temele .

**Comment by ineagu** [comment]
Aici link - https://make.wordpress.org/core/2014/07/08/customizer-improvements-in-4-0/
