### ISSUE TITLE
Multiple unescaped options found:

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Mooveit-Lite#92]
mooveit_lite_header_articletitle
mooveit_lite_header_articleentry
mooveit_lite_header_title - unescaped output in <a href="tel:'. get_theme_mod( 'mooveit_lite_header_subtitle' )
mooveit_lite_frontpage_secondlybox_content
etc.
@robciucioan @robi09

**Comment by ineagu** [comment]
Please check all theme options before resubmitting! See: Data Validation. Also, please note that esc_attr() is not always the appropriate escape function. esc_attr() is used when escaping HTML attributes such as alt, value, title. For strings such as titles or blocks of text use wp_kses_post()

**Comment by robciucioan** [comment]
@ineagu, acest issue l-am rezolvat în commit-ul pentru #87 și #88.
