### ISSUE TITLE
prefix styles

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/Mooveit-Lite#93]
Please prefix custom script and stylesheet handles in mooveit_lite_wp_enqueue_style_movatique() and mooveit_lite_wp_enqueue_script_movatique(), like so:
wp_enqueue_style( 'mooveit_lite_style', get_stylesheet_uri(), array(), '1.5' );

@robi09 @robciucioan

**Comment by robciucioan** [comment]
@ineagu & @robi09, când modific "mooveit_lite_wp_enqueue_style" în "wp_enqueue_style", îmi dă următoarea eroare:

 Cannot redeclare wp_enqueue_style() (previously declared in D:\Server\htdocs\WordPress\Mooveit\wp-includes\functions.wp-styles.php:158) in D:\Server\htdocs\WordPress\Mooveit\wp-content\themes\Mooveit-Lite\functions.php on line 93

**Comment by ineagu** [comment]
dar cine a zis sa modifici aia asa ?

**Comment by robi09** [comment]
@robciucioan ideea este sa modifici "style" in "mooveit_lite_style" la wp_enqueue_style( 'style', get_stylesheet_uri(), array(), '1.5' );

**Comment by robciucioan** [comment]
@robi09, ok.
