### ISSUE TITLE
Escape

### ISSUE THREAD

**Issue by robi09** [Codeinwp/Mooveit-Lite#97]
Multiple unescaped options found:
mooveit_lite_header_articletitle
mooveit_lite_header_articleentry
mooveit_lite_header_title - unescaped output in <a href="tel:'. get_theme_mod( 'mooveit_lite_header_subtitle' )
mooveit_lite_frontpage_secondlybox_content
etc.

**Comment by ineagu** [comment]
@robciucioan asta e facut ?

**Comment by robciucioan** [comment]
@ineagu & @robi09, am verificat din nou și sunt adăugate "esc_attr", "esc_url", "esc_textarea", etc.

**Comment by ineagu** [comment]
@robciucioan daca te uiti aici : https://github.com/Codeinwp/Mooveit-Lite/blob/48ba187762a30c1418c2df19dd8411647b94f5f9/includes/subheader.php, cand le afisezi nu le faci escape .

**Comment by robciucioan** [comment]
@ineagu, la mine este adăugat "esc_attr", "esc_textarea", "esc_url". S-a acceptat pull request-ul?
![image](https://cloud.githubusercontent.com/assets/8695094/6165616/0cfeba94-b2b2-11e4-86d8-5664aeb7ea3d.png)

**Comment by ineagu** [comment]
ok, deci este adaugat acu nu ?

**Comment by robciucioan** [comment]
@ineagu, la mine este adăugat. Trebuie doar să se dea accept la pull request.

**Comment by robciucioan** [comment]
@ineagu, pot închide acest issue?

**Comment by ineagu** [comment]
da
