### ISSUE TITLE
Prefix custom stylesheet

### ISSUE THREAD

**Issue by robi09** [Codeinwp/Mooveit-Lite#98]
Please prefix custom script and stylesheet handles in mooveit_lite_wp_enqueue_style_movatique() and mooveit_lite_wp_enqueue_script_movatique(), like so:
wp_enqueue_style( 'mooviet_lite_style', get_stylesheet_uri(), array(), '1.5' );

**Comment by ineagu** [comment]
@robciucioan asta e facut ?

**Comment by robciucioan** [comment]
@ineagu & @robi09, da... la mine este adăugat prefix: "mooveit_lite_style".
![image](https://cloud.githubusercontent.com/assets/8695094/6165571/afb0607c-b2b1-11e4-8059-a70fc5d44cd9.png)

**Comment by ineagu** [comment]
pai trebuie si pt nivo lightbox, font etc, scripts, ar trebuie
mooveit_lite_scripts, mooveit_lite_html5shiv etc

2015-02-12 11:22 GMT+01:00 Robciuc Ioan <notifications@github.com>:
